// Code generated by "stringer -type=DetectorID -linecomment"; DO NOT EDIT.

package catalog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GLOBAL-0]
	_ = x[Cloudflare-1]
	_ = x[PHP-2]
	_ = x[ApacheHTTPD-3]
	_ = x[LiteSpeed-4]
	_ = x[Nginx-5]
	_ = x[WordPress-6]
	_ = x[Laravel-7]
}

const _DetectorID_name = "GLOBALcloudflarephp-programming-languageapache-httpdlitespeednginxwordpresslaravel"

var _DetectorID_index = [...]uint8{0, 6, 16, 40, 52, 61, 66, 75, 82}

func (i DetectorID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DetectorID_index)-1 {
		return "DetectorID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DetectorID_name[_DetectorID_index[idx]:_DetectorID_index[idx+1]]
}
